### ISSUE TITLE
Asteroids - Todo list

### ISSUE THREAD

**Issue by cyan33** [thomasyimgit/Zion-demos#37]
- [x] Create and maintain a particle system for Asteroids or Bubbles 
- [x] Create the polygon shape for the asteroids
- [x] Extend your sprite drawing module to handle spritesheet based animation
- [x] Extend your math and physics libraries to handle collision necessary for the game of your choice
- [x] Extend your Heads-Up-Display module to display score
- [x] Create a system that allows you to create multiple levels based on variation of particle system parameters (location of particles, speed of particles, etc.). You can choose the features that you want to vary across multiple levels.
